In [1]:
!ls ./input

alter_info  deliveries.csv  matches.csv  PlayerInfo_Modified.csv


In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("./input/deliveries.csv")
df.head(2)

match_id  inning         batting_team                 bowling_team  over  \
0         1       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   
1         1       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   

   ball    batsman non_striker    bowler  is_super_over   ...    bye_runs  \
0     1  DA Warner    S Dhawan  TS Mills              0   ...           0   
1     2  DA Warner    S Dhawan  TS Mills              0   ...           0   

   legbye_runs  noball_runs  penalty_runs  batsman_runs  extra_runs  \
0            0            0             0             0           0   
1            0            0             0             0           0   

   total_runs  player_dismissed dismissal_kind fielder  
0           0               NaN            NaN     NaN  
1           0               NaN            NaN     NaN  

[2 rows x 21 columns]

In [4]:
mf=pd.read_csv("./input/matches.csv", index_col="id")
mf.head(2)

season       city        date                team1  \
id                                                       
1     2017  Hyderabad  2017-04-05  Sunrisers Hyderabad   
2     2017       Pune  2017-04-06       Mumbai Indians   

                          team2                  toss_winner toss_decision  \
id                                                                           
1   Royal Challengers Bangalore  Royal Challengers Bangalore         field   
2        Rising Pune Supergiant       Rising Pune Supergiant         field   

    result  dl_applied                  winner  win_by_runs  win_by_wickets  \
id                                                                            
1   normal           0     Sunrisers Hyderabad           35               0   
2   normal           0  Rising Pune Supergiant            0               7   

   player_of_match                                      venue         umpire1  \
id                                                                              
1     Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal     AY Dandekar   
2        SPD Smith    Maharashtra Cricket Association Stadium  A Nand Kishore   

     umpire2  umpire3  
id                     
1   NJ Llong      NaN  
2     S Ravi      NaN

In [5]:
bat_set=set(df["batsman"])
print(len(bat_set))

461


In [6]:
pdm=pd.read_csv("./output/till_orgin_id.csv", index_col="Name")
pdm.head(2)

Unnamed: 0                                             Search  \
Name                                                                            
A Ashish Reddy           1  http://search.espncricinfo.com/ci/content/play...   
A Chandila              32  http://search.espncricinfo.com/ci/content/play...   

                                          Profile Alternative Name  \
Name                                                                 
A Ashish Reddy  /india/content/player/389605.html     Ashish Reddy   
A Chandila       /india/content/player/27783.html    Ajit Chandila   

                                                            Image Origin  \
Name                                                                       
A Ashish Reddy  http://www.espncricinfo.com/db/PICTURES/CMS/14...  india   
A Chandila      http://www.espncricinfo.com/db/PICTURES/CMS/14...  india   

               Profile Id  
Name                       
A Ashish Reddy     389605  
A Chandila          27783

# Batsman

1. Strike Rate
* Batting Average
* No Of 4, 6
* No of Matches PLayed
* Win /Loose
* How to defeat him
* Most run
* Out After (Run Bins)


## 0. Update key value funtion

In [7]:
def update_variable(variable_name,variable, player_dict):
    player_dict[str(variable_name)]=variable
    

## Initalize Dictonary

In [8]:
p_name="CH Gayle"
player_dict={"name":p_name}
player_dict["type"]="batsman"
player_dict

{'name': 'CH Gayle', 'type': 'batsman'}

In [9]:
def get_pdf(p_name):
    pdf=df[df["batsman"]==p_name]
    return pdf

def get_pdf_s(p_name): 
    pdf_s=df[(df["batsman"]==p_name) | (df["non_striker"]==p_name) ]
    return pdf_s

In [10]:
pdf=get_pdf(p_name)
pdf_s=get_pdf_s(p_name)

## Get Origin and espncricinfo.com id

In [11]:
def origin_id(p_name, pdm, player_dict):
    origin=pdm.loc[p_name]["Origin"]
    profile_id=pdm.loc[p_name]["Profile Id"]
    update_variable("origin",origin, player_dict)
    update_variable("profile_id",profile_id, player_dict)
    return player_dict

player_dict=origin_id(p_name, pdm, player_dict)    

In [12]:
player_dict

{'name': 'CH Gayle',
 'type': 'batsman',
 'origin': 'westindies',
 'profile_id': '51880'}

## 1. Strike Rate

In [13]:
def strike_rate(pdf, player_dict):
    total_runs=sum(pdf["total_runs"])
    total_balls=pdf.shape[0]
    strike_rate=100*(total_runs/total_balls)
#     print(strike_rate)
    update_variable("strike_rate",strike_rate, player_dict)

### Saving Data
strike_rate(pdf, player_dict)
player_dict

{'name': 'CH Gayle',
 'type': 'batsman',
 'origin': 'westindies',
 'profile_id': '51880',
 'strike_rate': 154.58135860979462}

## 2. Batting Average

In [14]:
def batting_average(pdf, pdf_s, p_name, player_dict):
    
    total_runs=sum(pdf["total_runs"])
    times_dismised=pdf_s[pdf_s["player_dismissed"]==p_name].count()["player_dismissed"]
    
    batting_average=total_runs/times_dismised
    
#     print(batting_average)
    update_variable("batting_average",batting_average, player_dict)

### Saving Data
batting_average(pdf, pdf_s,p_name,player_dict)
player_dict

{'name': 'CH Gayle',
 'type': 'batsman',
 'origin': 'westindies',
 'profile_id': '51880',
 'strike_rate': 154.58135860979462,
 'batting_average': 43.97752808988764}

In [15]:
total_runs=sum(pdf["total_runs"])
total_runs
pdf_s

match_id  inning                 batting_team         bowling_team  \
125            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
126            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
127            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
128            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
129            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
130            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
131            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
132            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
133            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
134            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
135            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
136            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
137            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
138            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
139            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
140            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
141            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
142            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
143            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
144            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
145            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
146            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
147            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
148            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
149            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
151            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
152            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
153            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
154            1       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
...          ...     ...                          ...                  ...   
150373       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150374       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150375       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150376       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150377       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150378       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150379       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150380       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150381       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150382       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150383       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150384       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150385       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150386       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150387       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150388       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150389       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150390       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150391       636       2  Royal Challengers Bangalore  Sunrisers Hyderabad   
150392       636       2  Roya

## 3. No. of 4 and 6


In [16]:
def total_4_6(pdf, player_dict):
    total_4=pdf[pdf["total_runs"]==4].count()["total_runs"]
#     print(total_4)
    total_6=pdf[pdf["total_runs"]==6].count()["total_runs"]
#     print(total_6)
    update_variable("4s",total_4, player_dict)
    update_variable("6s",total_6, player_dict)
        
### Saving Data
total_4_6(pdf, player_dict)

## 4. No. of Matches Played

In [17]:
def no_of_matches(pdf_s, player_dict):
    no_of_matches=len(set(pdf_s["match_id"]))
#     print(no_of_matches)
    update_variable("no_of_matches",no_of_matches, player_dict)

no_of_matches(pdf_s, player_dict)

## 5. Wining percentage

In [18]:
mf.head(1)

season       city        date                team1  \
id                                                       
1     2017  Hyderabad  2017-04-05  Sunrisers Hyderabad   

                          team2                  toss_winner toss_decision  \
id                                                                           
1   Royal Challengers Bangalore  Royal Challengers Bangalore         field   

    result  dl_applied               winner  win_by_runs  win_by_wickets  \
id                                                                         
1   normal           0  Sunrisers Hyderabad           35               0   

   player_of_match                                      venue      umpire1  \
id                                                                           
1     Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal  AY Dandekar   

     umpire2  umpire3  
id                     
1   NJ Llong      NaN

In [19]:
def update_match_status(pdf_s, p_name):
    
    print("Match Status Started for:",p_name)
    match_ids=list(set(pdf_s["match_id"]))
    
    for m_id in match_ids:
        
        player_team  =  pdf_s[pdf_s["match_id"]==m_id].iloc[0]["batting_team"]
        winning_team =  mf.loc[m_id]["winner"]

        if winning_team==player_team:
            status="Winner"
        elif pd.isnull(winning_team):
            status="No Result"
        else:
            status="Looser"
            
            
        pdf_s.loc[pdf_s["match_id"]==m_id, "match_status"]=status
    


In [20]:
update_match_status(pdf_s, p_name)

Match Status Started for: CH Gayle


/home/boo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/home/boo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [21]:
pdf_s.head(1)

match_id  inning                 batting_team         bowling_team  over  \
125         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     1   

     ball   batsman    non_striker   bowler  is_super_over     ...       \
125     1  CH Gayle  Mandeep Singh  A Nehra              0     ...        

     legbye_runs  noball_runs  penalty_runs  batsman_runs  extra_runs  \
125            0            0             0             1           0   

     total_runs  player_dismissed  dismissal_kind fielder match_status  
125           1               NaN             NaN     NaN       Looser  

[1 rows x 22 columns]

In [22]:
def winning_percentage(pdf_s, player_dict):
    first_element_of_group=pdf_s.groupby(["match_id","match_status"]).first().reset_index()
    frequency=first_element_of_group["match_status"].value_counts()
    try: 
        won=frequency["Winner"]
    except:
        won=0
    try:    
        lost=frequency["Looser"]
    except:
        lost=0
    winning_percentage=100*won/(won+lost)
    winning_percentage=round(winning_percentage,2)
    update_variable("winning_percentage",winning_percentage, player_dict)

In [23]:
winning_percentage(pdf_s, player_dict)

## 6. Weakness

* Stratedgy For Ballers

In [24]:
pdf.head(1)

match_id  inning                 batting_team         bowling_team  over  \
125         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     1   

     ball   batsman    non_striker   bowler  is_super_over   ...    bye_runs  \
125     1  CH Gayle  Mandeep Singh  A Nehra              0   ...           0   

     legbye_runs  noball_runs  penalty_runs  batsman_runs  extra_runs  \
125            0            0             0             1           0   

     total_runs  player_dismissed dismissal_kind fielder  
125           1               NaN            NaN     NaN  

[1 rows x 21 columns]

In [25]:
dismissed_cols=df[df["dismissal_kind"].notnull()]["dismissal_kind"].unique()
### Saving Data

def dismissal_type(pdf,dismissed_cols,player_dict):
    for col in dismissed_cols:
        try:
            player_dict[col]=pdf["dismissal_kind"].value_counts()[col]
        except:
            player_dict[col]=0
            pass

In [26]:
dismissal_type(pdf, dismissed_cols,player_dict)
player_dict

{'name': 'CH Gayle',
 'type': 'batsman',
 'origin': 'westindies',
 'profile_id': '51880',
 'strike_rate': 154.58135860979462,
 'batting_average': 43.97752808988764,
 '4s': 306,
 '6s': 261,
 'no_of_matches': 100,
 'winning_percentage': 51.02,
 'caught': 55,
 'bowled': 22,
 'run out': 2,
 'lbw': 7,
 'caught and bowled': 2,
 'stumped': 2,
 'retired hurt': 0,
 'hit wicket': 0,
 'obstructing the field': 0}

## 7. Most Runs

In [27]:
def most_runs(pdf, player_dict):
    most_runs=max(pdf.groupby("match_id").sum()["total_runs"])

#     print(most_runs)
    ### Saving Data
    update_variable("most_runs",most_runs, player_dict)
most_runs(pdf, player_dict)

## 8.  Out After (Run Bins)

In [28]:
def update_bins(pdf,player_dict):
    value=pdf.groupby("match_id").sum()["total_runs"].values
    bins = [0,25,50,75,200]
    hist=np.histogram(value,bins)
    
    print(hist)
    for h in range(0,4):
        key_name=str(hist[1][h])+"-"+str(str(hist[1][h+1])+"s")
        
        try: 
            value=hist[0][h]
        except:
            value=0
        
        player_dict[key_name]=value
    

In [29]:
update_bins(pdf,player_dict)
player_dict


(array([47, 22, 10, 21]), array([  0,  25,  50,  75, 200]))


{'name': 'CH Gayle',
 'type': 'batsman',
 'origin': 'westindies',
 'profile_id': '51880',
 'strike_rate': 154.58135860979462,
 'batting_average': 43.97752808988764,
 '4s': 306,
 '6s': 261,
 'no_of_matches': 100,
 'winning_percentage': 51.02,
 'caught': 55,
 'bowled': 22,
 'run out': 2,
 'lbw': 7,
 'caught and bowled': 2,
 'stumped': 2,
 'retired hurt': 0,
 'hit wicket': 0,
 'obstructing the field': 0,
 'most_runs': 181,
 '0-25s': 47,
 '25-50s': 22,
 '50-75s': 10,
 '75-200s': 21}

## Final output

In [30]:
player_dict

{'name': 'CH Gayle',
 'type': 'batsman',
 'origin': 'westindies',
 'profile_id': '51880',
 'strike_rate': 154.58135860979462,
 'batting_average': 43.97752808988764,
 '4s': 306,
 '6s': 261,
 'no_of_matches': 100,
 'winning_percentage': 51.02,
 'caught': 55,
 'bowled': 22,
 'run out': 2,
 'lbw': 7,
 'caught and bowled': 2,
 'stumped': 2,
 'retired hurt': 0,
 'hit wicket': 0,
 'obstructing the field': 0,
 'most_runs': 181,
 '0-25s': 47,
 '25-50s': 22,
 '50-75s': 10,
 '75-200s': 21}

## Creating aggregator function

In [31]:
def complete_agrregator(p_name, df, mf, pdm):
    
    # Intialize Dict
    player_dict={"name":p_name}

    #Profile Type
    player_dict["type"]="batsman"
    
    #Get player Data
    pdf=get_pdf(p_name)
    pdf_s=get_pdf_s(p_name)
    
    # Get origin and Espencrickinfo.com id
    player_dict=origin_id(p_name, pdm, player_dict)
    
    
    #1. Strike Rate
    strike_rate(pdf, player_dict)
    
    #2. Batting Average
    batting_average(pdf,pdf_s, p_name, player_dict)
    
    #3. No Of 4, 6
    total_4_6(pdf, player_dict)
    
    #4. No of Matches PLayed
    no_of_matches(pdf_s, player_dict)
    
    
    #5. Win /Loose
    update_match_status(pdf_s, p_name)
    winning_percentage(pdf_s, player_dict)
    
    #6. How to defeat him
    dismissed_cols=df[df["dismissal_kind"].notnull()]["dismissal_kind"].unique()
    dismissal_type(pdf,dismissed_cols,player_dict)
    
    #7. Most run
    most_runs(pdf, player_dict)
    
    #8. Out After (Run Bins)
    update_bins(pdf,player_dict)

    return player_dict

# Running Test

In [32]:
df=pd.read_csv("./input/deliveries.csv")
mf=pd.read_csv("./input/matches.csv", index_col="id")
pdm=pd.read_csv("./output/till_orgin_id.csv", index_col="Name")


x=complete_agrregator("S Dhawan", df, mf, pdm)
x

Match Status Started for: S Dhawan
(array([63, 32, 25,  6]), array([  0,  25,  50,  75, 200]))


{'name': 'S Dhawan',
 'type': 'batsman',
 'origin': 'india',
 'profile_id': '28235',
 'strike_rate': 124.92512479201332,
 'batting_average': 34.440366972477065,
 '4s': 404,
 '6s': 70,
 'no_of_matches': 126,
 'winning_percentage': 49.21,
 'caught': 64,
 'bowled': 20,
 'run out': 13,
 'lbw': 5,
 'caught and bowled': 2,
 'stumped': 4,
 'retired hurt': 0,
 'hit wicket': 0,
 'obstructing the field': 0,
 'most_runs': 108,
 '0-25s': 63,
 '25-50s': 32,
 '50-75s': 25,
 '75-200s': 6}

# Mega Dictonary Creater fucntion:

In [33]:
def save_all(player_list):

    print("Started thread from:",player_list[0], "to", player_list[-1])
        
    
#     player_list=bat_set=set(df["batsman"])

    for player in player_list:
        p_name=str(player)
        player_dict=complete_agrregator(p_name,df, mf, pdm)
        player_dicts.append(player_dict)

    return player_dicts

In [34]:
# player_list=list(set(df["batsman"]))
# save_all(player_list[0:76])

# Multi Threading  for faster results

In [35]:
import threading
import math

#### Importing Csv File
df=pd.read_csv("./input/deliveries.csv")
mf=pd.read_csv("./input/matches.csv", index_col="id")
pdm=pd.read_csv("./output/till_orgin_id.csv", index_col="Name")


## Creating Main Dictonary
player_dicts=[]

## DIsrtibutiing workload 
player_list=list(set(df["batsman"]))
total_players=len(player_list)


## Setting Processor Power 
thread_count=8
delta=total_players/thread_count


## Making thread list
thread_list=[]
for i in range(thread_count):
    start=math.floor(i*delta)
    end=math.floor( (i+1)*delta)
    
    ## We are dealing with python list which starts form 0 and not 1
    list_end=total_players-1
    
    if end > list_end:
        end=list_end
    
    
    t=threading.Thread(target=save_all, args=(player_list[start:end],))
    thread_list.append(t)
    
    
    print("Start:", start, "End:", end)
    print("Start:", player_list[start], "End:", player_list[end])

Start: 0 End: 57
Start: S Ladda End: TA Boult
Start: 57 End: 115
Start: TA Boult End: UT Khawaja
Start: 115 End: 172
Start: UT Khawaja End: S Sreesanth
Start: 172 End: 230
Start: S Sreesanth End: B Chipli
Start: 230 End: 288
Start: B Chipli End: AA Jhunjhunwala
Start: 288 End: 345
Start: AA Jhunjhunwala End: AC Gilchrist
Start: 345 End: 403
Start: AC Gilchrist End: SR Watson
Start: 403 End: 460
Start: SR Watson End: LA Pomersbach


## Starting thread now

In [36]:
## Starting Thread
import time

start_time=time.time()

for t in thread_list:
    t.start()


## Rejoining Thread
for t in thread_list:
    t.join()

end_time=time.time()

Started thread from: S Ladda to R Bhatia
Started thread from: TA Boult to AA Noffke
Started thread from: UT Khawaja to HM Amla
Started thread from: S Sreesanth to SB Jakati
Started thread from: B Chipli to KL Rahul
Started thread from: AA Jhunjhunwala to M Manhas
Started thread from: AC Gilchrist to L Ablish
Started thread from: SR Watson to Rashid Khan
Match Status Started for: S Ladda
Match Status Started for: TA Boult
Match Status Started for: S Sreesanth
Match Status Started for: B Chipli
Match Status Started for:Match Status Started for: UT Khawaja
 AA Jhunjhunwala


/home/boo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in long_scalars
  


Match Status Started for: AC Gilchrist
(array([1, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: KW Richardson
Match Status Started for: SR Watson
(array([2, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([3, 1, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([4, 2, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: DB Das
Match Status Started for: OA Shah
(array([12,  0,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: MN van Wyk
(array([13,  1,  1,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: DP NannesMatch Status Started for: HH Gibbs

(array([18,  1,  2,  0]), array([  0,  25,  50,  75, 200]))
(array([2, 2, 0, 1]), array([  0,  25,  50,  75, 200]))
Match Status Started for: JJ Bumrah
(array([2, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: H Das
(array([18,  4,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: PP Ojha
Match Status Started for:(array(

Match Status Started for: KM Jadhav
Match Status Started for: SS Iyer
Match Status Started for: AC Thomas
(array([34, 23,  5,  1]), array([  0,  25,  50,  75, 200]))
(array([4, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: NM Coulter-Nile
(array([22,  1,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: S Badrinath
Match Status Started for: BR Dunk
(array([11,  0,  0,  0]), array([  0,  25,  50,  75, 200]))
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([18,  8,  4,  2]), array([  0,  25,  50,  75, 200]))
Match Status Started for: C Madan
Match Status Started for: TR Birt
(array([1, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: UBT Chand
Match Status Started for: M Rawat
(array([4, 1, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([39, 15,  3,  0]), array([  0,  25,  50,  75, 200]))
(array([31, 16,  5,  4]), array([  0,  25,  50,  75, 200]))
Match Status Started for:Match Status Started for: AL Mena

Match Status Started for: L Ronchi
Match Status Started for: Ankit Soni
(array([41, 16,  7,  0]), array([  0,  25,  50,  75, 200]))
(array([5, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([8, 1, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([56, 15,  5,  2]), array([  0,  25,  50,  75, 200]))
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))Match Status Started for: DR Smith

(array([45,  4,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: AD Nath
Match Status Started for: BE Hendricks
Match Status Started for: AN Ghosh
Match Status Started for: Niraj Patel
Match Status Started for: S Anirudha
(array([4, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([2, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([38,  6,  1,  0]), array([  0,  25,  50,  75, 200]))
(array([2, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: P Sahu
Match Status Started for: LR Shukla
Match Status Started for: Mohammad Asif
Match Status Started for:

/home/boo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in long_scalars
  


Match Status Started for: U Kaul
(array([12, 11,  0,  1]), array([  0,  25,  50,  75, 200]))
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: MK Pandey
(array([1, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: SD Chitnis
(array([33,  8,  1,  0]), array([  0,  25,  50,  75, 200]))Match Status Started for: MS Dhoni
Match Status Started for: S Nadeem

(array([27,  2,  1,  0]), array([  0,  25,  50,  75, 200]))(array([7, 1, 0, 0]), array([  0,  25,  50,  75, 200]))

(array([27, 27,  5,  3]), array([  0,  25,  50,  75, 200]))
Match Status Started for: R Sathish
Match Status Started for: TM Srivastava
Match Status Started for: AP Dole
Match Status Started for: R Dravid
(array([16,  0,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for:(array([1, 1, 0, 0]), array([  0,  25,  50,  75, 200])) P Awana
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))

Match Status Started for: I Sharma
Match Status Started for: R Mc

(array([7, 3, 1, 1]), array([  0,  25,  50,  75, 200]))
Match Status Started for:Match Status Started for: B Kumar
 RS Sodhi
Match Status Started for: AJ Finch
(array([83, 35, 14,  2]), array([  0,  25,  50,  75, 200]))(array([16,  7,  3,  3]), array([  0,  25,  50,  75, 200]))

Match Status Started for: AA Bilakhia
(array([1, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: AB Agarkar
Match Status Started for: ST Jayasuriya
(array([18, 12,  5,  1]), array([  0,  25,  50,  75, 200]))
Match Status Started for: CK Langeveldt
(array([6, 1, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([32,  1,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: MK Tiwary
(array([2, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: JA Morkel
(array([33, 12,  4,  1]), array([  0,  25,  50,  75, 200]))
(array([17,  1,  0,  0]), array([  0,  25,  50,  75, 200]))
Match Status Started for:Match Status Started for: P Negi
 Jaskaran Singh
Match Statu

Match Status Started for: PD Collingwood
Match Status Started for: LPC Silva
(array([31,  9,  5,  0]), array([  0,  25,  50,  75, 200]))
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: CJ Ferguson
Match Status Started for: (array([6, 3, 0, 0]), array([  0,  25,  50,  75, 200]))
CRD Fernando
Match Status Started for: DA Miller
(array([4, 0, 2, 1]), array([  0,  25,  50,  75, 200]))
Match Status Started for: N Rana
(array([2, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: VY Mahesh
Match Status Started for: KK Nair
(array([8, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([5, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: A Nehra
Match Status Started for: S Aravind
(array([7, 4, 4, 0]), array([  0,  25,  50,  75, 200]))
Match Status Started for: Rashid Khan
(array([3, 0, 0, 0]), array([  0,  25,  50,  75, 200]))
(array([10,  0,  0,  0]), array([  

In [37]:
pda=pd.DataFrame(player_dicts)

# Removing batsman with Inf or Zero batting avergae

In [38]:
pda=pda[ pda["batting_average"]!=0]
pda=pda[ pda["batting_average"]!=np.inf]
pda=pda[ pda["batting_average"]!=np.inf]
pda=pda[ pda["most_runs"]>4]

In [39]:
pda

0-25s  25-50s   4s  50-75s   6s  75-200s  batting_average  bowled  \
2        3       1    2       0    1        0        12.000000       0   
3        4       2   14       0    3        0        22.333333       0   
4       12       0    7       0    0        0        11.000000       1   
5       13       1   20       1    5        0        18.076923       2   
6       18       1   29       2    7        0        19.466667       4   
7        2       2   18       0    1        1        58.333333       1   
9       18       4   23       0   16        0        22.928571       4   
10      12       6   35       3   23        1        36.666667       3   
11       6       0    1       0    1        0        13.000000       0   
13       7       0    4       0    1        0        11.500000       0   
14      19       0    0       0    0        0         1.833333       3   
15       8       0    9       0    1        0        24.000000       3   
17       8       1    7       0    2        0        11.555556       0   
18      14       0    3       0    1        0         6.714286       4   
19      21       7   84       7   31        1        29.843750       7   
20       3       0    3       0    0        0        10.333333       0   
21      43      24  240       8   92        5        29.144737      12   
22       7       1    9       0   10        0        27.000000       1   
23       5       1   13       1    3        0        16.285714       1   
24      55      26  259      10  122        7        32.282353      27   
25       4       0    1       0    0        0         5.500000       0   
26      16       0    2       0    0        0         3.000000       3   
27       4       0    0       0    1        0         5.000000       3   
28       4       1   11       0    0        0        21.750000       0   
29       3       0    1       0    1        0        25.000000       0   
30      15       2   23       0    2        0        18.700000       4   
31      29      11  200      11   52        7        40.470588      15   
32       2       0    1       0    0        0        13.000000       1   
33       5       0    1       0    2        0         9.000000       1   
34       2       1    9       0    1        0        30.000000       0   
..     ...     ...  ...     ...  ...      ...              ...     ...   
427      1       0    0       0    2        0        14.000000       0   
428     17       8   61       5   24        0        31.791667       7   
429      2       2   11       0    5        0        29.750000       0   
430     58      25  278      12  123        8        30.255102      16   
431      3       0    3       0    0        0        13.500000       1   
432     14       1   26       1    2        0        16.733333       2   
433      5       0    9       0    0        0        11.200000       1   
435      1       0    0       0    0        0        10.000000       0   
436      9       0    1       0    0        0         3.666667       1   
437     13       0    4       0    2        0         7.000000       1   
438      5       0   12       1    8        0        26.400000       0   
439      6       1   22       1    3        0        19.500000       0   
440      6       3   31       1   23        2        41.000000       3   
441     10       1    5       0    1        0         9.000000       3   
442      3       2   30       1    2        1        30.142857       1   
443     15       0    4       0    0        0        14.000000       1   
445     51      26  257      15   44        3        30.200000      16   
446     71      34  388      23  159       13        38.881356      24   
447      5       0    3       0    0        0        29.000000       0   
448      3       0    2       0    1        0        13.500000       0   
449      1       0    1       0    0        0        11.000000       0   
450     88      25  242      19  149        1        31.285714       8   
451     1

In [40]:
pda.to_csv("./output/batsman.csv")

In [41]:
# pda.to_csv("batsman.csv")

In [42]:
print("Time Taken:", str(end_time-start_time),"sec" )

Time Taken: 316.8555417060852 sec
